import { Partner, SupportMaterial } from './types';

export const PARTNERS: Partner[] = [
  {
    id: 'marilaine_miranda',
    name: 'Consultório Odontológico Mariláine Miranda',
    discount: 'Consulte descontos exclusivos',
    category: 'Bem-estar',
    description: 'Localizado em Barra do Mendes. Atendimento odontológico de excelência com condições e facilidades exclusivas para associados.',
    logoColor: 'from-blue-600 to-red-600',
    telephone: '74 99108-2043',
    website: 'https://instagram.com/comm_06',
    exclusiveMaterials: ['post_desconto_parceiro'],
    city: 'Barra do Mendes'
  },
  {
    id: 'thesan_pet',
    name: 'Thesan Pet',
    discount: 'Desconto exclusivo Bahia Prev (consultar parceiro)',
    category: 'Outros',
    description: 'Localizado em Irecê. Tudo para o seu animal de estimação com as melhores marcas e preços sob tabela diferenciada.',
    logoColor: 'from-red-500 to-blue-700',
    telephone: '74 99905-4135',
    website: 'https://instagram.com/thesanpet',
    exclusiveMaterials: ['post_desconto_parceiro'],
    city: 'Irecê'
  },
  {
    id: 'hospital_sim',
    name: 'Hospital Sim',
    discount: 'Desconto exclusivo Bahia Prev (consultar clínica)',
    category: 'Bem-estar',
    description: 'Localizado em Irecê. Hospital Geral equipado para consultas e exames de diversas especialidades com tabela diferenciada.',
    logoColor: 'from-blue-700 to-red-500',
    telephone: '74 99984-6644',
    website: 'https://instagram.com/hospitalsimirece',
    exclusiveMaterials: ['post_informativo_atendimento'],
    city: 'Irecê'
  },
  {
    id: 'templum_implantes',
    name: 'Templum | Implantes Dentários em Irecê',
    discount: 'Desconto exclusivo Bahia Prev (consultar clínica)',
    category: 'Bem-estar',
    description: 'Localizado em Irecê. Especialistas em implantes dentários, estética e reabilitação oral com qualidade garantida.',
    logoColor: 'from-blue-800 to-red-600',
    telephone: '74 99981-1575',
    website: 'https://instagram.com/templumimplante',
    exclusiveMaterials: ['post_desconto_parceiro'],
    city: 'Irecê'
  },
  {
    id: 'dr_checape',
    name: 'Clínica Dr. Checape',
    discount: 'R$ 100 off na consulta',
    category: 'Bem-estar',
    description: 'Localizado em Irecê. Diagnóstico médico rápido, consultas acessíveis e exames laboratoriais.',
    logoColor: 'from-red-600 to-blue-600',
    telephone: '74 99807-2222',
    website: 'https://instagram.com/drchecape',
    exclusiveMaterials: ['post_informativo_atendimento'],
    city: 'Irecê'
  },
  {
    id: 'menina_dos_oculos',
    name: 'Óticas Menina dos Óculos',
    discount: 'Desconto exclusivo Bahia Prev (consultar parceiro)',
    category: 'Ótica',
    description: 'Localizado em Irecê. Ampla gama de armações nacionais e importadas e lentes de alto desempenho.',
    logoColor: 'from-blue-600 to-red-500',
    telephone: '74 99999-2879',
    website: 'https://instagram.com/oticameninairece',
    exclusiveMaterials: ['post_desconto_parceiro'],
    city: 'Irecê'
  },
  {
    id: 'sao_rafael',
    name: 'Ótica São Rafael',
    discount: 'Descontos em armações e lentes',
    category: 'Ótica',
    description: 'Localizado em Irecê / Região. Armações modernas e lentes corretivas com descontos especiais de parceria.',
    logoColor: 'from-red-500 to-blue-800',
    telephone: '71 98314-3810',
    website: 'https://instagram.com/oticas_sao_rafael',
    exclusiveMaterials: ['post_desconto_parceiro'],
    city: 'Irecê'
  },
  {
    id: 'audio_clinica',
    name: 'Audio Clínica',
    discount: 'Condições especiais em saúde auditiva',
    category: 'Bem-estar',
    description: 'Localizado em Irecê. Consultas e aparelhos auditivos de alta tecnologia para melhorar sua qualidade de vida.',
    logoColor: 'from-blue-700 to-red-600',
    telephone: '74 99923-0109',
    website: 'https://instagram.com/audioclinicairece',
    exclusiveMaterials: ['post_informativo_atendimento'],
    city: 'Irecê'
  },
  {
    id: 'multimagem',
    name: 'Clínica Multimagem',
    discount: 'Desconto exclusivo Bahia Prev (consultar clínica)',
    category: 'Bem-estar',
    description: 'Localizado em Irecê. Exames de imagem avançados, ultrassonografia, raio-x e exames especializados.',
    logoColor: 'from-blue-600 to-blue-900',
    telephone: '74 3641-4436',
    website: 'https://instagram.com/multimagemclinica',
    exclusiveMaterials: ['post_informativo_atendimento'],
    city: 'Irecê'
  },
  {
    id: 'otica_familia',
    name: 'Ótica Família.com',
    discount: 'Descontos exclusivos em óculos e exames',
    category: 'Ótica',
    description: 'Localizado em Irecê. Armações modernas e lentes personalizadas com ótimos descontos de convênio.',
    logoColor: 'from-red-600 to-red-800',
    telephone: '74 99909-8283',
    website: 'https://instagram.com/oticafamilia_com',
    exclusiveMaterials: ['post_desconto_parceiro'],
    city: 'Irecê'
  },
  {
    id: 'ortoclinica',
    name: 'Ortoclínica',
    discount: 'Até 40% de desconto em consultas',
    category: 'Bem-estar',
    description: 'Localizado em Barreiras / Região. Atendimento especializado em ortopedia e traumatologia para você cuidar do seu corpo.',
    logoColor: 'from-blue-800 to-blue-600',
    telephone: '77 99978-3843',
    website: 'https://instagram.com/ortoclinica_brrs',
    exclusiveMaterials: ['post_desconto_parceiro'],
    city: 'Barreiras'
  },
  {
    id: 'cdi_barreiras',
    name: 'CDI Centro de Diagnóstico por Imagens',
    discount: 'Até 45% de desconto em exames',
    category: 'Bem-estar',
    description: 'Localizado em Barreiras. Desconto variável dependendo do exame de imagem realizado com tecnologia de ponta.',
    logoColor: 'from-blue-600 to-red-600',
    telephone: '77 99978-3843',
    website: 'https://instagram.com/cdibarreiras',
    exclusiveMaterials: ['post_desconto_parceiro'],
    city: 'Barreiras'
  },
  {
    id: 'clinica_yona',
    name: 'Clínica Yoná',
    discount: 'Até 40% de desconto em atendimento',
    category: 'Bem-estar',
    description: 'Localizado em Barreiras. Consultas e exames em diversas especialidades médicas com descontos exclusivos.',
    logoColor: 'from-red-600 to-blue-700',
    telephone: '77 99921-6664',
    website: 'https://instagram.com/yonaclinicamedica',
    exclusiveMaterials: ['post_desconto_parceiro'],
    city: 'Barreiras'
  },
  {
    id: 'rafa_gas',
    name: 'Rafa Gás',
    discount: '10% na entrega | 7% para retirada',
    category: 'Outros',
    description: 'Localizado em Barreiras. Gás de cozinha e água mineral de qualidade, com entrega super ágil e ótimo preço.',
    logoColor: 'from-blue-600 to-red-500',
    telephone: '77 99947-4732',
    website: 'https://instagram.com/rafa_gas_e_agua',
    exclusiveMaterials: ['post_desconto_parceiro'],
    city: 'Barreiras'
  },
  {
    id: 'bioanalise',
    name: 'BioAnálise Laboratório',
    discount: 'Até 40% de desconto em exames',
    category: 'Bem-estar',
    description: 'Localizado em Barreiras. Exames laboratoriais de rotina e de alta complexidade com rigoroso controle de qualidade.',
    logoColor: 'from-blue-700 to-blue-900',
    telephone: '77 3611-0910',
    website: 'https://instagram.com/bioanalise.brrs',
    exclusiveMaterials: ['post_desconto_parceiro'],
    city: 'Barreiras'
  },
  {
    id: 'drogaria_ferreira',
    name: 'Drogaria Ferreira JD',
    discount: 'Descontos especiais em medicamentos',
    category: 'Farmácia',
    description: 'Localizado em João Dourado. Medicamentos e perfumaria com facilidades e descontos de parceiro.',
    logoColor: 'from-red-600 to-blue-600',
    telephone: '74 99967-2716',
    website: 'https://instagram.com/drogariaferreirajd',
    exclusiveMaterials: ['post_desconto_parceiro'],
    city: 'João Dourado'
  },
  {
    id: 'centro_medico_bahia',
    name: 'Centro Médico da Bahia',
    discount: 'Preços especiais sob consulta',
    category: 'Bem-estar',
    description: 'Localizado em Jussara. Amplo corpo clínico e atendimento humanizado para exames e consultas médicas.',
    logoColor: 'from-blue-600 to-red-600',
    telephone: '74 9816-2793',
    website: 'https://instagram.com/cmbjussara',
    exclusiveMaterials: ['post_informativo_atendimento'],
    city: 'Jussara'
  },
  {
    id: 'nb_centro_medico',
    name: 'NB Centro Médico Odontológico',
    discount: '15% de desconto em exames lab.',
    category: 'Bem-estar',
    description: 'Localizado em Morro do Chapéu. Consultas médicas, atendimento odontológico e exames de laboratório.',
    logoColor: 'from-blue-800 to-red-600',
    telephone: '74 99940-3834',
    website: 'https://instagram.com/nbcentro',
    exclusiveMaterials: ['post_desconto_parceiro'],
    city: 'Morro do Chapéu'
  },
  {
    id: 'oticas_mundi',
    name: 'Óticas Mundi Wanderley',
    discount: 'Descontos de convênio exclusivos',
    category: 'Ótica',
    description: 'Localizado em Wanderley. Lentes e armações modernas para realçar seu olhar com descontos especiais.',
    logoColor: 'from-red-600 to-blue-900',
    telephone: '77 99913-3045',
    website: 'https://instagram.com/oticasmundiwanderleyba',
    exclusiveMaterials: ['post_desconto_parceiro'],
    city: 'Wanderley'
  },
  {
    id: 'gas_souza',
    name: 'Gás Souza',
    discount: '1,48% de desconto exclusivo',
    category: 'Outros',
    description: 'Localizado na região de Wanderley. Gás de cozinha seguro e confiável com benefício em folha/convênio.',
    logoColor: 'from-blue-500 to-red-600',
    telephone: '73 99960-5915',
    city: 'Wanderley'
  },
  {
    id: 'academia_power',
    name: 'Academia Power',
    discount: '10% de desconto em mensalidades',
    category: 'Bem-estar',
    description: 'Localizado em Wanderley. Musculação e atividade física com estrutura adequada. Falar com instrutor Beto.',
    logoColor: 'from-blue-700 to-red-600',
    telephone: '77 99913-8555',
    website: 'https://www.instagram.com/academiapowerofficial/',
    exclusiveMaterials: ['post_desconto_parceiro'],
    city: 'Wanderley'
  },
  {
    id: 'supermercado_santa_vitoria',
    name: 'Supermercado Santa Vitória',
    discount: 'Até 10% de desconto em compras',
    category: 'Alimentação',
    description: 'Localizado na região de Wanderley. Alimentos, higiene e utilidades domésticas. Falar com Suzana.',
    logoColor: 'from-red-600 to-blue-600',
    telephone: '77 99911-6444',
    website: 'https://instagram.com/supermercadosanta_vitoria',
    exclusiveMaterials: ['post_desconto_parceiro'],
    city: 'Wanderley'
  },
  {
    id: 'distribuidora_pinguim',
    name: 'Distribuidora Pinguim',
    discount: '5,56% de desconto em compras',
    category: 'Alimentação',
    description: 'Localizado em Wanderley. Sua distribuidora completa de bebidas, água, gelo e carvão.',
    logoColor: 'from-blue-600 to-red-500',
    telephone: '77 98818-1675',
    website: 'https://instagram.com/dst.pinguim',
    exclusiveMaterials: ['post_desconto_parceiro'],
    city: 'Wanderley'
  },
  {
    id: 'farma_voce',
    name: 'FarmaVocê',
    discount: 'Consulte os descontos em loja',
    category: 'Farmácia',
    description: 'Localizado em Wanderley. Completa variedade em medicamentos, genéricos e perfumaria com preços competitivos.',
    logoColor: 'from-red-500 to-blue-600',
    telephone: '77 99809-6675',
    website: 'https://instagram.com/farmavocewanderleyba',
    exclusiveMaterials: ['post_desconto_parceiro'],
    city: 'Wanderley'
  },
  {
    id: 'oral_smile',
    name: 'Oral Smile Clínica Odontológica',
    discount: 'Condições especiais e facilidades',
    category: 'Bem-estar',
    description: 'Localizado em Barreiras. Implantes, próteses, ortodontia e estética dental com profissionais altamente qualificados.',
    logoColor: 'from-blue-600 to-red-600',
    telephone: '77 99898-4145',
    website: 'https://instagram.com/oral.smilebarreiras',
    exclusiveMaterials: ['post_desconto_parceiro'],
    city: 'Barreiras'
  },
  {
    id: 'consultorio_hilda_nery',
    name: 'Consultório Odontológico Hilda Nery',
    discount: 'Desconto exclusivo Bahia Prev (consultar clínica)',
    category: 'Bem-estar',
    description: 'Localizado em Cafarnaum. Consultas clínicas e tratamentos odontológicos com dedicação e atendimento qualificado.',
    logoColor: 'from-blue-800 to-red-500',
    telephone: '74 98833-2215',
    website: 'https://instagram.com/consultorioodontodrahildanery',
    exclusiveMaterials: ['post_desconto_parceiro'],
    city: 'Cafarnaum'
  }
];

export const SUPPORT_MATERIALS: SupportMaterial[] = [
  {
    id: 'post_desconto_parceiro',
    title: 'Post Redes Sociais: Descontos de Parceiros',
    category: 'Redes Sociais',
    format: 'PNG (Otimizado)',
    dimensions: '1080 x 1080 px (1:1)',
    description: 'Post quadrado perfeito para feed de Instagram e Facebook divulgando descontos de parceiros.',
    accentColor: 'from-blue-500 to-red-500',
    templateType: 'post_desconto'
  },
  {
    id: 'banner_todos_convenios',
    title: 'Banner Web: Rede Credenciada',
    category: 'Banners',
    format: 'PNG / SVG',
    dimensions: '1920 x 1080 px (16:9)',
    description: 'Banner em alta definição para sites ou banners físicos divulgando os benefícios da parceria.',
    accentColor: 'from-blue-600 to-red-600',
    templateType: 'banner_convenio'
  },
  {
    id: 'post_informativo_atendimento',
    title: 'Post Redes Sociais: Suporte e Atendimento',
    category: 'Redes Sociais',
    format: 'PNG (Otimizado)',
    dimensions: '1080 x 1080 px (1:1)',
    description: 'Post informativo focado em atendimento humanizado, facilitado e descontos de agendamento.',
    accentColor: 'from-blue-500 to-red-600',
    templateType: 'post_informativo'
  }
];
